tiger:
  id: 100
  name: 王大炮
  age: 500
  isMarried: false
  birthday: 2000/11/11
#  对象写法
#  car: {name: 宝马, price: 200000}
  car:
    name: 宝马
    price: 30000

  skill: [skill,skill2]
  hobby: [1,2,3,4]
  wife: {no1: 1, no2: 2, no3: 3}
  salaries: [10000,10000]
  cars:
    group1:
      - {name: 奔驰, price: 99999}
      - name: 保时捷
        price: 202020
spring:
  mvc:
#    设置前缀
    static-path-pattern: /springboot/**
    hiddenmethod:
      filter:
        enabled: true
    view:
      prefix: /springboot/
      suffix: .html
  web:
    resources:
      static-locations: []
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ssm?useSSL=true&amp;useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: PO1!pVRNJp4i
    driver-class-name: com.mysql.jdbc.Driver
server:
#  配置端口
  port: 9090
  tomcat:
    threads:
      max: 200
      min-spare: 5
    accept-count: 200
    max-connections: 2000
    connection-timeout: 10000